# Generated by Django 2.2.4 on 2019-08-18 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to='Api.LearningPath'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='submission',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
